spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://49.235.216.182:15432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  application:
    name: weixin-server
  weixin:
    currentUserName: wxid_45irb1z1yl4d12
    adminKey: 999222
    authCode: b126fc11-00f8-4479-8266-35d2bd2b698c
    baseUrl: http://49.235.216.182:1238/
    sendMessageURl: message/SendTextMessage
    connect : ws://49.235.216.182:1238/ws/GetSyncMsg?key=
  qq:
    token: Aa792144169
    baseUrl: http://49.235.216.182:3000/
    websocket:
      url: ws://49.235.216.182:3001/
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-4c481a3983b5447697d6972172cef392
      chat:
        options:
          model: deepseek-chat
    ollama:
      base-url: http://49.235.216.182:11434
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 1536
    vectorstore:
      pgvector:
        datasource:
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: postgres
          url: jdbc:postgresql://49.235.216.182:15432/postgres
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            maximum-pool-size: 5
            minimum-idle: 2
            idle-timeout: 30000
            connection-timeout: 30000
    mcp:
      client:
        sse:
          connections:
            mcp-server-csdn:
              url: http://49.235.216.182:8101
            mcp-server-context7:
              url: http://122.51.46.6:5001
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml


server:
  port: 8080

#logging:
#  level:
#    com.zzw.infrastuction.dao: debug  # 你的 Mapper 接口包
#    org.mybatis: debug                # MyBatis 主包
#    java.sql: debug                   # SQL 层（JDBC）