spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: xxxxxx
    password: xxxxxx
    url: jdbc:postgresql://49.xxxxxx:15432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  application:
    name: weixin-server
  weixin:
    currentUserName: xxxxxx
    adminKey: xxxxxx
    authCode: b126fc11-00f8-xxxxxx-8266-35d2bd2b698c
    baseUrl: http://49.xxxxxx.216.182:xxxxxx/
    sendMessageURl: message/SendTextMessage
    connect : ws://49.235.xxxxxx.182:1238/ws/GetSyncMsg?key=
  qq:
    token: xxxxxx
    baseUrl: http://49.235.xxxxxx.182:3000/
    websocket:
      url: ws://49.235.xxxxxx.182:3001/


  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-xxxxxx
      chat:
        options:
          model: xxxxxx-chat
    ollama:
      base-url: http://49.xxxxxx.216.182:11434
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 1536
    vectorstore:
      pgvector:
        datasource:
          driver-class-name: org.postgresql.Driver
          username: xxxxxx
          password: xxxxxx
          url: jdbc:postgresql://49.xxxxxx.xxxxxx.182:xxxxxx/postgres
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            maximum-pool-size: 5
            minimum-idle: 2
            idle-timeout: 30000
            connection-timeout: 30000
    mcp:
      client:
        sse:
          connections:
            mcp-server-csdn:
              url: http://49.235.216.xxxxxx:xxxxxx
            mcp-server-context7:
              url: http://122.51.xxxxxx.6:xxxxxx
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml


server:
  port: 8080

#logging:
#  level:
#    com.zzw.infrastuction.dao: debug  # 你的 Mapper 接口包
#    org.mybatis: debug                # MyBatis 主包
#    java.sql: debug                   # SQL 层（JDBC）
